// Code generated by specgen. DO NOT EDIT.

package main

import (
	"github.com/krew-solutions/ascetic-ddd-go/asceticddd/option"

	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
)

// UndiscountedSpecAST returns AST for UndiscountedSpec
func UndiscountedSpecAST() spec.Visitable {
	return spec.IsNull(spec.Field(spec.GlobalScope(), "Discount"))
}

// WellDiscountedSpecAST returns AST for WellDiscountedSpec
func WellDiscountedSpecAST() spec.Visitable {
	return spec.And(spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount")), spec.GreaterThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(10)))
}

// NotWellDiscountedSpecAST returns AST for NotWellDiscountedSpec
func NotWellDiscountedSpecAST() spec.Visitable {
	return spec.Not(spec.And(spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount")), spec.GreaterThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(10))))
}

// DiscountedBySpecAST returns AST for DiscountedBySpec
func DiscountedBySpecAST(by option.Option[int]) spec.Visitable {
	return spec.EqualityOrNullTest("=", spec.Field(spec.GlobalScope(), "Discount"), spec.Value(by))
}

// DiscountedByFiveSpecAST returns AST for DiscountedByFiveSpec
func DiscountedByFiveSpecAST() spec.Visitable {
	return spec.Equal(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(5))
}

// HasDiscountSpecAST returns AST for HasDiscountSpec
func HasDiscountSpecAST() spec.Visitable {
	return spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount"))
}

// DiscountedOverSpecAST returns AST for DiscountedOverSpec
func DiscountedOverSpecAST(limit option.Option[int]) spec.Visitable {
	return spec.And(spec.IsNotNull(spec.Value(limit)), spec.And(spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount")), spec.GreaterThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(limit))))
}

// NotDiscountedOverSpecAST returns AST for NotDiscountedOverSpec
func NotDiscountedOverSpecAST(limit option.Option[int]) spec.Visitable {
	return spec.Not(spec.And(spec.IsNotNull(spec.Value(limit)), spec.And(spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount")), spec.GreaterThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(limit)))))
}

// UndiscountedOrUnderSpecAST returns AST for UndiscountedOrUnderSpec
func UndiscountedOrUnderSpecAST() spec.Visitable {
	return spec.Or(spec.IsNull(spec.Field(spec.GlobalScope(), "Discount")), spec.LessThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(10)))
}

// GuardedOverSpecAST returns AST for GuardedOverSpec
func GuardedOverSpecAST(limit option.Option[int]) spec.Visitable {
	return spec.And(spec.And(spec.IsNotNull(spec.Value(limit)), spec.IsNotNull(spec.Field(spec.GlobalScope(), "Discount"))), spec.GreaterThan(spec.Field(spec.GlobalScope(), "Discount"), spec.Value(limit)))
}

