// Code generated by specgen. DO NOT EDIT.

package main

import (
	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
)

// HasRegionWithExpensiveItemsSpecAST returns AST for HasRegionWithExpensiveItemsSpec
func HasRegionWithExpensiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Regions"), spec.Wildcard(spec.Object(spec.Item(), "Categories"), spec.Wildcard(spec.Object(spec.Item(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000)))))
}

// HasActiveRegionWithPremiumItemsSpecAST returns AST for HasActiveRegionWithPremiumItemsSpec
func HasActiveRegionWithPremiumItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Regions"), spec.And(spec.Field(spec.Item(), "Active"), spec.Wildcard(spec.Object(spec.Item(), "Categories"), spec.And(spec.Field(spec.Item(), "Active"), spec.Wildcard(spec.Object(spec.Item(), "Items"), spec.And(spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000)), spec.Field(spec.Item(), "Active")))))))
}

// ActiveOrgWithExpensiveItemsSpecAST returns AST for ActiveOrgWithExpensiveItemsSpec
func ActiveOrgWithExpensiveItemsSpecAST() spec.Visitable {
	return spec.And(spec.Field(spec.GlobalScope(), "Active"), spec.Wildcard(spec.Object(spec.GlobalScope(), "Regions"), spec.Wildcard(spec.Object(spec.Item(), "Categories"), spec.Wildcard(spec.Object(spec.Item(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(10000))))))
}

// NoRegionWithExpensiveItemsSpecAST returns AST for NoRegionWithExpensiveItemsSpec
func NoRegionWithExpensiveItemsSpecAST() spec.Visitable {
	return spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Regions"), spec.Wildcard(spec.Object(spec.Item(), "Categories"), spec.Wildcard(spec.Object(spec.Item(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(100000))))))
}

