// Code generated by specgen. DO NOT EDIT.

package main

import (
	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
)

// ActiveStoreSpecAST returns AST for ActiveStoreSpec
func ActiveStoreSpecAST() spec.Visitable {
	return spec.Field(spec.GlobalScope(), "Active")
}

// NamedStoreSpecAST returns AST for NamedStoreSpec
func NamedStoreSpecAST() spec.Visitable {
	return spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value(""))
}

// HasExpensiveItemsSpecAST returns AST for HasExpensiveItemsSpec
func HasExpensiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(1000)))
}

// AllItemsActiveSpecAST returns AST for AllItemsActiveSpec
func AllItemsActiveSpecAST() spec.Visitable {
	return spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Not(spec.Field(spec.Item(), "Active"))))
}

// HasCheapItemsSpecAST returns AST for HasCheapItemsSpec
func HasCheapItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(100)))
}

// HasItemInStockSpecAST returns AST for HasItemInStockSpec
func HasItemInStockSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Stock"), spec.Value(0)))
}

// HasAffordableActiveItemsSpecAST returns AST for HasAffordableActiveItemsSpec
func HasAffordableActiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.And(spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(500)), spec.Field(spec.Item(), "Active")))
}

// HasPremiumItemsSpecAST returns AST for HasPremiumItemsSpec
func HasPremiumItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.And(spec.And(spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000)), spec.GreaterThan(spec.Field(spec.Item(), "Stock"), spec.Value(0))), spec.Field(spec.Item(), "Active")))
}

// HasDiscountedExpensiveItemsSpecAST returns AST for HasDiscountedExpensiveItemsSpec
func HasDiscountedExpensiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Sub(spec.Field(spec.Item(), "Price"), spec.Value(100)), spec.Value(900)))
}

// HasTaxedCheapItemsSpecAST returns AST for HasTaxedCheapItemsSpec
func HasTaxedCheapItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.LessThan(spec.Add(spec.Field(spec.Item(), "Price"), spec.Div(spec.Field(spec.Item(), "Price"), spec.Value(10))), spec.Value(110)))
}

// HasItemWithShiftedIDSpecAST returns AST for HasItemWithShiftedIDSpec
func HasItemWithShiftedIDSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Equal(spec.LeftShift(spec.Field(spec.Item(), "ID"), spec.Value(2)), spec.Value(8)))
}

// PremiumActiveStoreSpecAST returns AST for PremiumActiveStoreSpec
func PremiumActiveStoreSpecAST() spec.Visitable {
	return spec.And(spec.And(spec.Field(spec.GlobalScope(), "Active"), spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value(""))), spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(1000))))
}

// BudgetFriendlyStoreSpecAST returns AST for BudgetFriendlyStoreSpec
func BudgetFriendlyStoreSpecAST() spec.Visitable {
	return spec.And(spec.Field(spec.GlobalScope(), "Active"), spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Not(spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(1000))))))
}

// NoExpensiveItemsSpecAST returns AST for NoExpensiveItemsSpec
func NoExpensiveItemsSpecAST() spec.Visitable {
	return spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000))))
}

// NotAllItemsActiveSpecAST returns AST for NotAllItemsActiveSpec
func NotAllItemsActiveSpecAST() spec.Visitable {
	return spec.Not(spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Not(spec.Field(spec.Item(), "Active")))))
}

