// Code generated by specgen. DO NOT EDIT.

package main

import (
	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
	infra "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/infrastructure"
)

// ActiveStoreSpecAST returns AST for ActiveStoreSpec
func ActiveStoreSpecAST() spec.Visitable {
	return spec.Field(spec.GlobalScope(), "Active")
}

// ActiveStoreSpecSQL returns SQL for ActiveStoreSpec
func ActiveStoreSpecSQL() (string, []any, error) {
	ast := ActiveStoreSpecAST()
	return infra.CompileToSQL(ast)
}

// NamedStoreSpecAST returns AST for NamedStoreSpec
func NamedStoreSpecAST() spec.Visitable {
	return spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value(""))
}

// NamedStoreSpecSQL returns SQL for NamedStoreSpec
func NamedStoreSpecSQL() (string, []any, error) {
	ast := NamedStoreSpecAST()
	return infra.CompileToSQL(ast)
}

// HasExpensiveItemsSpecAST returns AST for HasExpensiveItemsSpec
func HasExpensiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(1000)))
}

// HasExpensiveItemsSpecSQL returns SQL for HasExpensiveItemsSpec
func HasExpensiveItemsSpecSQL() (string, []any, error) {
	ast := HasExpensiveItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// AllItemsActiveSpecAST returns AST for AllItemsActiveSpec
func AllItemsActiveSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Field(spec.Item(), "Active"))
}

// AllItemsActiveSpecSQL returns SQL for AllItemsActiveSpec
func AllItemsActiveSpecSQL() (string, []any, error) {
	ast := AllItemsActiveSpecAST()
	return infra.CompileToSQL(ast)
}

// HasCheapItemsSpecAST returns AST for HasCheapItemsSpec
func HasCheapItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(100)))
}

// HasCheapItemsSpecSQL returns SQL for HasCheapItemsSpec
func HasCheapItemsSpecSQL() (string, []any, error) {
	ast := HasCheapItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// HasItemInStockSpecAST returns AST for HasItemInStockSpec
func HasItemInStockSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Stock"), spec.Value(0)))
}

// HasItemInStockSpecSQL returns SQL for HasItemInStockSpec
func HasItemInStockSpecSQL() (string, []any, error) {
	ast := HasItemInStockSpecAST()
	return infra.CompileToSQL(ast)
}

// HasAffordableActiveItemsSpecAST returns AST for HasAffordableActiveItemsSpec
func HasAffordableActiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.And(spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(500)), spec.Field(spec.Item(), "Active")))
}

// HasAffordableActiveItemsSpecSQL returns SQL for HasAffordableActiveItemsSpec
func HasAffordableActiveItemsSpecSQL() (string, []any, error) {
	ast := HasAffordableActiveItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// HasPremiumItemsSpecAST returns AST for HasPremiumItemsSpec
func HasPremiumItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.And(spec.And(spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000)), spec.GreaterThan(spec.Field(spec.Item(), "Stock"), spec.Value(0))), spec.Field(spec.Item(), "Active")))
}

// HasPremiumItemsSpecSQL returns SQL for HasPremiumItemsSpec
func HasPremiumItemsSpecSQL() (string, []any, error) {
	ast := HasPremiumItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// HasDiscountedExpensiveItemsSpecAST returns AST for HasDiscountedExpensiveItemsSpec
func HasDiscountedExpensiveItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Sub(spec.Field(spec.Item(), "Price"), spec.Value(100)), spec.Value(900)))
}

// HasDiscountedExpensiveItemsSpecSQL returns SQL for HasDiscountedExpensiveItemsSpec
func HasDiscountedExpensiveItemsSpecSQL() (string, []any, error) {
	ast := HasDiscountedExpensiveItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// HasTaxedCheapItemsSpecAST returns AST for HasTaxedCheapItemsSpec
func HasTaxedCheapItemsSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.LessThan(spec.Add(spec.Field(spec.Item(), "Price"), spec.Div(spec.Field(spec.Item(), "Price"), spec.Value(10))), spec.Value(110)))
}

// HasTaxedCheapItemsSpecSQL returns SQL for HasTaxedCheapItemsSpec
func HasTaxedCheapItemsSpecSQL() (string, []any, error) {
	ast := HasTaxedCheapItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// HasItemWithFlagSpecAST returns AST for HasItemWithFlagSpec
func HasItemWithFlagSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Equal(spec.Value(nil) /* TODO: unsupported op & */, spec.Value(1)))
}

// HasItemWithFlagSpecSQL returns SQL for HasItemWithFlagSpec
func HasItemWithFlagSpecSQL() (string, []any, error) {
	ast := HasItemWithFlagSpecAST()
	return infra.CompileToSQL(ast)
}

// HasItemWithShiftedIDSpecAST returns AST for HasItemWithShiftedIDSpec
func HasItemWithShiftedIDSpecAST() spec.Visitable {
	return spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Equal(spec.LeftShift(spec.Field(spec.Item(), "ID"), spec.Value(2)), spec.Value(8)))
}

// HasItemWithShiftedIDSpecSQL returns SQL for HasItemWithShiftedIDSpec
func HasItemWithShiftedIDSpecSQL() (string, []any, error) {
	ast := HasItemWithShiftedIDSpecAST()
	return infra.CompileToSQL(ast)
}

// PremiumActiveStoreSpecAST returns AST for PremiumActiveStoreSpec
func PremiumActiveStoreSpecAST() spec.Visitable {
	return spec.And(spec.And(spec.Field(spec.GlobalScope(), "Active"), spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value(""))), spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(1000))))
}

// PremiumActiveStoreSpecSQL returns SQL for PremiumActiveStoreSpec
func PremiumActiveStoreSpecSQL() (string, []any, error) {
	ast := PremiumActiveStoreSpecAST()
	return infra.CompileToSQL(ast)
}

// BudgetFriendlyStoreSpecAST returns AST for BudgetFriendlyStoreSpec
func BudgetFriendlyStoreSpecAST() spec.Visitable {
	return spec.And(spec.Field(spec.GlobalScope(), "Active"), spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.LessThan(spec.Field(spec.Item(), "Price"), spec.Value(1000))))
}

// BudgetFriendlyStoreSpecSQL returns SQL for BudgetFriendlyStoreSpec
func BudgetFriendlyStoreSpecSQL() (string, []any, error) {
	ast := BudgetFriendlyStoreSpecAST()
	return infra.CompileToSQL(ast)
}

// NoExpensiveItemsSpecAST returns AST for NoExpensiveItemsSpec
func NoExpensiveItemsSpecAST() spec.Visitable {
	return spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.GreaterThan(spec.Field(spec.Item(), "Price"), spec.Value(5000))))
}

// NoExpensiveItemsSpecSQL returns SQL for NoExpensiveItemsSpec
func NoExpensiveItemsSpecSQL() (string, []any, error) {
	ast := NoExpensiveItemsSpecAST()
	return infra.CompileToSQL(ast)
}

// NotAllItemsActiveSpecAST returns AST for NotAllItemsActiveSpec
func NotAllItemsActiveSpecAST() spec.Visitable {
	return spec.Not(spec.Wildcard(spec.Object(spec.GlobalScope(), "Items"), spec.Field(spec.Item(), "Active")))
}

// NotAllItemsActiveSpecSQL returns SQL for NotAllItemsActiveSpec
func NotAllItemsActiveSpecSQL() (string, []any, error) {
	ast := NotAllItemsActiveSpecAST()
	return infra.CompileToSQL(ast)
}

