// Code generated by specgen. DO NOT EDIT.

package main

import (
	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
)

// AdultUserSpecAST returns AST for AdultUserSpec
func AdultUserSpecAST() spec.Visitable {
	return spec.GreaterThanEqual(spec.Field(spec.GlobalScope(), "Age"), spec.Value(18))
}

// ActiveUserSpecAST returns AST for ActiveUserSpec
func ActiveUserSpecAST() spec.Visitable {
	return spec.Equal(spec.Field(spec.GlobalScope(), "Active"), spec.Value(true))
}

// ValidEmailSpecAST returns AST for ValidEmailSpec
func ValidEmailSpecAST() spec.Visitable {
	return spec.NotEqual(spec.Field(spec.GlobalScope(), "Email"), spec.Value(""))
}

// PremiumUserSpecAST returns AST for PremiumUserSpec
func PremiumUserSpecAST() spec.Visitable {
	return spec.And(spec.And(spec.GreaterThanEqual(spec.Field(spec.GlobalScope(), "Age"), spec.Value(18)), spec.Field(spec.GlobalScope(), "Active")), spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value("")))
}

// YoungUserSpecAST returns AST for YoungUserSpec
func YoungUserSpecAST() spec.Visitable {
	return spec.LessThan(spec.Field(spec.GlobalScope(), "Age"), spec.Value(25))
}

// InactiveUserSpecAST returns AST for InactiveUserSpec
func InactiveUserSpecAST() spec.Visitable {
	return spec.Not(spec.Field(spec.GlobalScope(), "Active"))
}

