// Code generated by specgen. DO NOT EDIT.

package main

import (
	spec "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/domain"
	infra "github.com/krew-solutions/ascetic-ddd-go/asceticddd/specification/infrastructure"
)

// AdultUserSpecAST returns AST for AdultUserSpec
func AdultUserSpecAST() spec.Visitable {
	return spec.GreaterThanEqual(spec.Field(spec.GlobalScope(), "Age"), spec.Value(18))
}

// AdultUserSpecSQL returns SQL for AdultUserSpec
func AdultUserSpecSQL() (string, []any, error) {
	ast := AdultUserSpecAST()
	return infra.CompileToSQL(ast)
}

// ActiveUserSpecAST returns AST for ActiveUserSpec
func ActiveUserSpecAST() spec.Visitable {
	return spec.Equal(spec.Field(spec.GlobalScope(), "Active"), spec.Value(true))
}

// ActiveUserSpecSQL returns SQL for ActiveUserSpec
func ActiveUserSpecSQL() (string, []any, error) {
	ast := ActiveUserSpecAST()
	return infra.CompileToSQL(ast)
}

// ValidEmailSpecAST returns AST for ValidEmailSpec
func ValidEmailSpecAST() spec.Visitable {
	return spec.NotEqual(spec.Field(spec.GlobalScope(), "Email"), spec.Value(""))
}

// ValidEmailSpecSQL returns SQL for ValidEmailSpec
func ValidEmailSpecSQL() (string, []any, error) {
	ast := ValidEmailSpecAST()
	return infra.CompileToSQL(ast)
}

// PremiumUserSpecAST returns AST for PremiumUserSpec
func PremiumUserSpecAST() spec.Visitable {
	return spec.And(spec.And(spec.GreaterThanEqual(spec.Field(spec.GlobalScope(), "Age"), spec.Value(18)), spec.Field(spec.GlobalScope(), "Active")), spec.NotEqual(spec.Field(spec.GlobalScope(), "Name"), spec.Value("")))
}

// PremiumUserSpecSQL returns SQL for PremiumUserSpec
func PremiumUserSpecSQL() (string, []any, error) {
	ast := PremiumUserSpecAST()
	return infra.CompileToSQL(ast)
}

// YoungUserSpecAST returns AST for YoungUserSpec
func YoungUserSpecAST() spec.Visitable {
	return spec.LessThan(spec.Field(spec.GlobalScope(), "Age"), spec.Value(25))
}

// YoungUserSpecSQL returns SQL for YoungUserSpec
func YoungUserSpecSQL() (string, []any, error) {
	ast := YoungUserSpecAST()
	return infra.CompileToSQL(ast)
}

// InactiveUserSpecAST returns AST for InactiveUserSpec
func InactiveUserSpecAST() spec.Visitable {
	return spec.Not(spec.Field(spec.GlobalScope(), "Active"))
}

// InactiveUserSpecSQL returns SQL for InactiveUserSpec
func InactiveUserSpecSQL() (string, []any, error) {
	ast := InactiveUserSpecAST()
	return infra.CompileToSQL(ast)
}

