package specification

// Specification is a predicate of T and its tree: IsSatisfiedBy answers for
// a candidate in memory, and Expression is the same predicate as a tree, for
// a repository to compile with its context, or to evaluate. A type with
// IsSatisfiedBy marked `//spec:sql` gets Expression generated by specgen.
type Specification[T any] interface {
	IsSatisfiedBy(candidate T) bool
	Expression() Visitable
}
